import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import { getCurrentSession } from "@/actions/auth";

export const metadata: Metadata = {
  title: "Temo Ecommerce",
  description: "Generated by create next app",
};
const inter = Inter({subsets: ['latin']})
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {user} = await getCurrentSession();
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-white text-black`}
      >
        <Header user={user}/>
        {children}
      </body>
    </html>
  );
}
